# Generated by Django 4.2 on 2023-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('round', models.IntegerField()),
                ('object', models.CharField(max_length=200)),
                ('response', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
