# Generated by Django 4.2 on 2023-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ideamarks_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('object_key', models.CharField(max_length=155)),
            ],
        ),
    ]
