# Generated by Django 4.2 on 2023-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_objectkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='key_type',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
