# Generated by Django 4.2 on 2023-06-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userkey_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='key_type',
            field=models.IntegerField(default=0),
        ),
    ]
