# Generated by Django 4.2 on 2023-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userround'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='prolific_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
