# Generated by Django 4.2 on 2023-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userkey_prolific_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideamarks',
            name='object_index',
            field=models.IntegerField(default=0),
        ),
    ]
