# Generated by Django 4.2 on 2023-07-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ideamarks_object_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideamarks',
            old_name='user_id',
            new_name='userkey_id',
        ),
        migrations.RenameField(
            model_name='userround',
            old_name='user_id',
            new_name='userkey_id',
        ),
    ]
